on:
  push:
    branches-ignore:
      - main
  workflow_call:


jobs:
  tests:
    runs-on: ubuntu-24.04
    env:
      NPM_CONFIG_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install composer dependencies
        run: composer install -n --prefer-dist --ansi
      - name: Install node dependencies
        run: npm install
      - name: Setup config
        run: cp .env.example .env && ./artisan key:generate --ansi
      - name: Build assets
        run: npm run build
      - name: Run tests
        run: ./artisan test --ansi

name: Run tests
