on:
  push:
    branches-ignore:
      - main
  workflow_call:


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: composer install -n --prefer-dist && npm install
      - name: Setup config
        run: cp .env.example .env && ./artisan key:generate
      - name: Build assets
        run: npm run build
      - name: Run tests
        run: ./artisan test

name: Run tests
